# Change these first
owner: morganism # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

# __dangerous__disable_verify_peer: true
# __dangerous__disable_verify_host: true
# OR both in 1
# __dangerous__insecure: true
# 
sites:
  - name: PASS Test 200
    url: https://git.morganism.dev/upptime
  - name: FAIL Test 404
    url: https://git.morganism.dev/morganism.dev/status
    icon: https://avatars.githubusercontent.com/u/1324390?s=48&v=4
    expectedStatusCodes:
      - 302
      - 404
  - name: Home Webhook Listener
    check: "tcp-ping"
    url: $WEBHOOKS_MORGANISM_DEV_URL
    port: 8888
  - name: Home Status
    url: "$HOME_STATUS_URL:$HOME_STATUS_PORT"
  - name: Home VPN 
    check: "tcp-ping"
    port: $SSH_HOME_SZIRAKI_CO_UK_PORT
    url: $SSH_HOME_SZIRAKI_CO_UK_URL
  - name: RemoteLock Web Portal
    url: https://smartlock.devicewebmanager.com/
  - name: RemoteLock API Service
    url: https://api.remotelock.com
    expectedStatusCodes:
      - 401
  - name: EC2 Docker Box
    url: https:/ec2-3-11-207-176.eu-west-2.compute.amazonaws.com:9443//
    expectedStatusCodes:
      - 200
  - name: Pipedream
    url: https://status.pipedream.com/
  - name: Hive
    url: https://status.hivehome.com
assignees:  
  - morganism

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: git.morganism.dev
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/1324390?v=4
  name: Morganism @ rareMedium.ltd
  introTitle: "The status page for apps and services I tend"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/$OWNER/$REPO). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: https://github.com/morganism/upptime#readme
    - title: Git Morganism
      href: https://git.$OWNER.dev/$REPO
    - title: Blog
      href: https://blog.sziraki.co.uk/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
